<div class="card login-form">
  <div class="form-header">
    <a href="/?q=auth/signup">Don't have an account?</a>
  </div>
  <h2>Welcome</h2>
  <form method="post">

    <div class="fld">
      <input type="email" name="email" placeholder=" " required>
      <label>Email</label>
    </div>
    <div class="fld">
      <input type="password" name="password" placeholder=" " required>
      <label>Password</label>
    </div>

    <div class="button-set form-footer">
      <a href="/?q=auth/forgot">Forgot password?</a>
      <button class="btn recaptcha-btn" id="login-btn" type="submit">Login</button>
    </div>
    <?php include __DIR__ . '/../common/recaptcha.phtml'; ?>
  </form>
</div>