<?php

use App\Model\Account\User;

$requestModel = $this->var('serviceModel');
$completeData = $requestModel->getCompleteData();
$completeAt = new DateTimeImmutable($requestModel->get('completed_at'));
$attachments = $requestModel->getAttachments();
?>
<style>
    #complete-details {
        max-width: 600px;
    }
</style>
<div class="entity-form card" id="complete-details">
    <h3>Completion Details</h3>
    <div class="fld">
        <input type="date" disabled value="<?= htmlspecialchars($completeAt->format('Y-m-d')) ?>">
        <label>Completed At:</label>
    </div>
    
    <div class="fld">
        <input type="number" disabled value="<?= htmlspecialchars($completeData['temperature']) ?>" step="0.1" min="0" max="100">
        <label>Temperature (°F):</label>
    </div>

    <div class="fld">
        <input type="number" disabled value="<?= htmlspecialchars($completeData['wind']) ?>" step="0.1" min="0" max="100">
        <label>Wind Speed (MPH):</label>
    </div>
    <div class="fld">
        <input type="number" disabled value="<?= htmlspecialchars($completeData['exposure_hours']) ?>" step="1" min="0">
        <label>Restricted Exposure Hours (per label):</label>
    </div>
    <div class="fld">
        <input type="text" disabled value="<?= htmlspecialchars($completeData['water_used']['volume']) ?>">
        <label>Water Total:</label>
    </div>

    <?php include __DIR__ . '/form_components/attachments.phtml'; ?>
    
    <div class="button-set">
        <button type="button" class="btn cancel" onclick="window.history.back()">Back</button>
    <?php if (User::isAdmin()): ?>
        <button class="btn" type="button" onclick="document.getElementById('attachment-modal').classList.add('show')">Add attachment</button>
    <?php endif ?>
    </div>
    <?php if (User::isAdmin()): ?>
    <?php include __DIR__ . '/dialog/attachment.phtml'; ?>
    <?php endif; ?>
</div>