<footer class="flex" style="justify-content:space-between;align-items:center;padding:1rem">
  <div>
    <h4>Contact Us</h4>
    <a href="tel:509-449-8989">509-449-8989</a><br>
    PO Box 64<br>
    Manson, WA. 98831<br>
    <a href="mailto:portal@aghawkdynamics.com">portal@aghawkdynamics.com</a><br>

  </div>

  <div class="right flex" style="gap:.6rem;align-items:center; font-family: 'Orbitron', sans-serif; font-size: 1.5rem;">
    <div>
      <span>AG</span><span>HAWK</span>
      <br> 
      DYNAMICS
    </div>
    <a href="https://www.facebook.com/profile.php?id=61566182047013" target="_blank"><img src="/public/img/social/ftrSocialFB.png" alt="Facebook" width="36" height="36"></a>
    <a href="https://www.instagram.com/aghawk.dynamics/" target="_blank"><img src="/public/img/social/ftrSocialIG.png" alt="Instagram" width="36" height="36"></a>
    <a href="https://www.youtube.com/@Aghawk.Dynamics" target="_blank"><img src="/public/img/social/ftrSocialYT.png" alt="YouTube" width="36" height="36"></a>
    <a href="https://www.x.com/AghawkDynamics" target="_blank"><img src="/public/img/social/ftrSocialX.png" alt="X (Twitter)" width="36" height="36"></a>
    <a href="https://www.tiktok.com/@aghawkdynamics" target="_blank"><img src="/public/img/social/ftrSocialTT.png" alt="TikTok"  width="36" height="36"></a>
  </div>
</footer>
<script>
  // Ensure the footer is always at the bottom
  document.addEventListener('DOMContentLoaded', function() {
    document.body.click(); // Trigger a click to make elements on their places
  });
</script>
</body>

</html>