<?php

use App\Model\Account\User;
?>

<div class="burger" id="navToggle" role="button" aria-label="Toggle navigation menu" aria-expanded="false" tabindex="0">
    <div></div>
    <div></div>
    <div></div>
</div>

<nav class="top-nav" role="navigation">
    <ul>
        <?php if (User::isAdmin()): ?>
            <li class="dropdown">
                <a class="top-link" href="/account">Accounts</a>
                <div class="dropdown-content">
                    <a href="/account/admin/create">Create</a>
                </div>
            </li>
        <?php endif; ?>

        <li class="dropdown">
            <a class="top-link" href="/parcel">Parcels</a>
            <div class="dropdown-content">
                <?php if (!User::isAdmin()): ?>
                    <a href="/parcel">List All</a>
                    <a href="/parcel/add">Add new parcel</a>
                <?php endif; ?>
            </div>
        </li>
        <li class="dropdown">
            <a class="top-link" href="/block">Blocks</a>
            <div class="dropdown-content">
                <?php if (!User::isAdmin()): ?>
                    <a href="/block">List All</a>
                    <a href="/block/add">Add Block</a>
                <?php endif; ?>
            </div>
        </li>
        <li class="dropdown">
            <a class="top-link" href="/service">Activity</a>
            <div class="dropdown-content">
                <?php if (!User::isAdmin()): ?>
                    <a href="/service">List All</a>
                    <a href="/service/request" class="hover-brand-yellow">Request Service</a>
                    <?php if (User::getInstance()->getAccount()->isSubscribed()): ?>
                        <a href="/service/track" class="hover-brand-green">
                            Self Tracking
                            <span class="badge-plus badge-plus-nav">+</span>
                        </a>
                    <?php endif ?>
                <?php endif; ?>
            </div>
        </li>
        <?php if (User::isAdmin()): ?>
            <!--li class="dropdown">
                <a class="top-link" href="/admin/config">Config</a>
            </li-->
        <?php endif; ?>
    </ul>
</nav>